title: "Bigpicture DOI demo"
description: "Demo for Bigpicture landing page"

theme: "jekyll-theme-cayman"
baseurl: /datasets.bp.nbis.se

collections:
  datasets:
    output: true
    layout: "dataset.html"
    permalink: ":path"
  parserdatasets:
    output: true
    layout: "parser_test.html"
    permalink: ":path"

  
defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "parserdatasets"
    values:
      layout: "parser_test"